Bump infoblox provider version to 1.1.1, terraform to 1.0+
BrownUniversity/terraform-infoblox-record-a pull request #8
Opened 2021-06-25 19:03 UTC by broestls

Updates the module with Terraform 1.0 series support as well as the provider version. 

Note that the provider has silently dropped the `network_view_name` provider between `1.0.4` and `1.1.1`. It is not documented why, but we also don't require a custom value here. Impact appears to be low for now.

2021-06-25 20:07 UTC, mirestrepo approved these changes
The changes look reasonable to me, but I wonder why the tests dis not run?

2021-06-25 20:09 UTC, mirestrepo commented
oh... I remember now - I think they have to be manually triggered. This is because this runs on internal runner, but repo is public so we don't want changes from PRs to run automatically

2021-06-25 20:10 UTC, mirestrepo requested changes
You'll need to update the version of the docker and the path. See maybe the project module for related updates

2021-07-14 23:42 UTC, broestls commented
I think I've resolved the requested issues, but I am spending a lot more time than I'd like trying to resolve issues with getting the `dorny/paths-filter` action to run. Probably will need some assistance there.

2021-07-21 21:23 UTC, mirestrepo requested changes
Can you also document in the README the environment variables that need to be set for the infoblox provider to work?

2021-07-21 21:23 UTC, mirestrepo commented on .github/workflows/kitchen-tests.yml
> +          INFOBLOX_PASSWORD: ${{ secrets.INFOBLOX_JHUB_USER}}
`INFOBLOX_PASSWORD` is incorrectly set to `${{ secrets.INFOBLOX_JHUB_USER}}`

2021-07-26 13:24 UTC, merged